
export const roles = [
  "All",
  "Executive",
  "Activities",
  "Technical",
  "Public Relations",
  "Media",
];

export const team = [

            /* EXECUTIVES */

  {
    id: 1,
    name: "Adam Serhan",
    role: "President",
    category:"Executive",
    bio: "Embedded systems nerd. Final-year EE student. Runs the firmware track and organizes the annual IoT showcase.",
    skills: ["ESP32", "FreeRTOS", "Rust"],
    img:" ",
    github: "#",
    linkedin: "#",
  },
  {
    id: 2,
    name: "Ali Elatly",
    role: "Vice-President",
    category:"Executive",
    bio: "Full-stack engineer focused on the cloud side of IoT — dashboards, APIs, and the pipelines that connect devices to data.",
    skills: ["Node-RED", "InfluxDB", "Grafana"],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 3,
    name: "Aseil AlShazly",
    role: "Treasurer",
    category:"Executive",
    bio: "Money, just money.",
    skills: ["Arduino", "Python", "MQTT"],
    img:" ",
    github: "#",
    linkedin: "#",
  },
  {
    id: 4,
    name: "Mohammed Arsh",
    role: "Executive Director",
    category:"Executive",
    bio: "Designs PCBs for fun. Obsessed with low-power design and LoRa long-range networks. Has bricked more boards than most people have seen.",
    skills: ["KiCad", "LoRa", "STM32"],
    img:" ",
    github: "#",
    linkedin: "#",
  },


  
            /* ACTIVITIES */
  {
    id: 5,
    name: "Hashir Hameed",
    role: "Activities Coordinator",
    category:"Activities",
    bio: "Designs and runs our workshop program. Believes anyone can learn hardware if the docs are good enough.",
    skills: ["React", "AWS IoT", "TimescaleDB"],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 6,
    name: "Shafie hashi",
    role: "Activities Team",
    category:"Activities",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 7,
    name: "Mada Salamah",
    role: "Activities Team",
    category:"Activities",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 8,
    name: "Jaida Abdullah",
    role: "Activities Team",
    category:"Activities",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 9,
    name: "Vanishri Shekhawat",
    role: "Activities Team",
    category:"Activities",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 10,
    name: "Mohammad Samer Al Talleh",
    role: "Activities Team",
    category:"Activities",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 11,
    name: "Marwan Saied",
    role: "Activities Team",
    category:"Activities",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },





  
            /* TECHNICAL */
  {
    id: 12,
    name: "Adam Farag ",
    role: "Technical Coordinator",
    category:"Technical",
    bio: "Keeps the Discord alive, organizes socials, and makes sure every new member feels welcome from day one.",
    skills: ["Community", "Events", "Communications"],
    img:" ",
    github: "#",
    linkedin: "#",
  },
  {
    id: 13,
    name: "Jana Shahin ",
    role: "Technical Team",
    category:"Technical",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 14,
    name: "Zaineh Hatamleh ",
    role: "Technical Team",
    category:"Technical",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 15,
    name: "Salahaldeen Jamhour ",
    role: "Technical Team",
    category:"Technical",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 16,
    name: "Abdul Sameen",
    role: "Technical Team",
    category:"Technical",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 17,
    name: "Yusuf Sabuwala",
    role: "Technical Team",
    category:"Technical",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  


  
            /* PUBLIC RELATIONS */
  {
    id: 18,
    name: "Saachi Motwani",
    role: "PR Coordinator",
    category: "Public Relations",
    bio: "Keeps the Discord alive, organizes socials, and makes sure every new member feels welcome from day one.",
    skills: ["Community", "Events", "Communications"],
    img:" ",
    github: "#",
    linkedin: "#",
  },
  {
    id: 19,
    name: "",
    role: "PR Team",
    category:"Public Relations",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 20,
    name: "",
    role: "PR Team",
    category:"Public Relations",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 21,
    name: "",
    role: "PR Team",
    category:"Public Relations",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 22,
    name: "",
    role: "PR Team",
    category:"Public Relations",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 23,
    name: "",
    role: "PR Team",
    category:"Public Relations",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },

  
            /* MEDIA */
  {
    id: 24,
    name: "Ahad Ali Suchedina",
    role: "Media Coordinator",
    category:"Media",
    bio: "Keeps the Discord alive, organizes socials, and makes sure every new member feels welcome from day one.",
    skills: ["Community", "Events", "Communications"],
    img:" ",
    github: "#",
    linkedin: "#",
  },
  {
    id: 25,
    name: "Eyad Wafa",
    role: "Media Team",
    category:"Media",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },{
    id: 26,
    name: "Mumtahina Tasnia",
    role: "Media Team",
    category:"Media",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 27,
    name: "Zeina Alaya",
    role: "Media Team",
    category:"Media",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 28,
    name: "Ali hussein",
    role: "Media Team",
    category:"Media",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 29,
    name: "",
    role: "Media Team",
    category:"Media",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },
  {
    id: 30,
    name: "",
    role: "Media Team",
    category:"Media",
    bio: " ",
    skills: ["", " ", " "],
    img:" ",
    github: "#",
    twitter: "#",
  },



];

export const advisors = [
  {
    id: 1,
    name: "Prof. Dr. Anastassia Gharib",
    role: "Faculty Advisor",    
    dept: "Dept. of Computer Science and Engineering",
    note: "Specialist in IoT",
    img:" ",
  },
];
